In [1]:
#importing liabraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, accuracy_score, classification_report
from sklearn.metrics import confusion_matrix
import warnings
warnings.filterwarnings("ignore")

%matplotlib inline
plt.style.use('seaborn')

In [2]:
# importing datasets
train=pd.read_csv("train_values.csv",index_col = 0)
labels=pd.read_csv("train_labels.csv",index_col = 0)
test=pd.read_csv("test_values.csv",index_col = 0)
# adding labels to train dataset
train["damage_grade"]=labels["damage_grade"]
print("shape of the train dataset is : ",train.shape)
print("shape of the test dataset is  : ",test.shape)

shape of the train dataset is :  (260601, 39)
shape of the test dataset is  :  (86868, 38)

In [3]:
# checking the types of varibles in the dataset(int,float,object)
dtypes=pd.DataFrame(train.dtypes,columns=["Data Type"])
dtypes["Unique Values"]=train.nunique()
dtypes["Null Values"]=train.isnull().sum()
dtypes["% null Values"]=train.isnull().sum()/len(train)
dtypes

,Data Type,Unique Values,Null Values,% null Values
geo_level_1_id,int64,31,0,0.0
geo_level_2_id,int64,1414,0,0.0
geo_level_3_id,int64,11595,0,0.0
count_floors_pre_eq,int64,9,0,0.0
age,int64,42,0,0.0
area_percentage,int64,84,0,0.0
height_percentage,int64,27,0,0.0
land_surface_condition,object,3,0,0.0
foundation_type,object,5,0,0.0
roof_type,object,3,0,0.0
ground_floor_type,object,5,0,0.0
other_floor_type,object,4,0,0.0
position,object,4,0,0.0
plan_configuration,object,10,0,0.0
has_superstructure_adobe_mud,int64,2,0,0.0
has_superstructure_mud_mortar_stone,int64,2,0,0.0
has_superstructure_stone_flag,int64,2,0,0.0
has_superstructure_cement_mortar_stone,int64,2,0,0.0
has_superstructure_mud_mortar_brick,int64,2,0,0.0
has_superstructure_cement_mortar_brick,int64,2,0,0.0
has_superstructure_timber,int64,2,0,0.0
has_superstructure_bamboo,int64,2,0,0.0
has_superstructure_rc_non_engineered,int64,2,0,0.0
has_superstructure_rc_engineered,int64,2,0,0.0
has_superstructure_other,int64,2,0,0.0
legal_ownership_status,object,4,0,0.0
count_families,int64,10,0,0.0
has_secondary_use,int64,2,0,0.0
has_secondary_use_agriculture,int64,2,0,0.0
has_secondary_use_hotel,int64,2,0,0.0
has_secondary_use_rental,int64,2,0,0.0
has_secondary_use_institution,int64,2,0,0.0
has_secondary_use_school,int64,2,0,0.0
has_secondary_use_industry,int64,2,0,0.0
has_secondary_use_health_post,int64,2,0,0.0
has_secondary_use_gov_office,int64,2,0,0.0
has_secondary_use_use_police,int64,2,0,0.0
has_secondary_use_other,int64,2,0,0.0
damage_grade,int64,3,0,0.0

In [4]:
# exploring the statstical fearures of train dataset (object).
train.describe(include="object").T

                         count unique top    freq
land_surface_condition  260601      3   t  216757
foundation_type         260601      5   r  219196
roof_type               260601      3   n  182842
ground_floor_type       260601      5   f  209619
other_floor_type        260601      4   q  165282
position                260601      4   s  202090
plan_configuration      260601     10   d  250072
legal_ownership_status  260601      4   v  250939

In [5]:
train.head()

,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,roof_type,...,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other,damage_grade
building_id,,,,,,,,,,,,,,,,,,,,,
802906,6,487,12198,2,30,6,5,t,r,n,...,0,0,0,0,0,0,0,0,0,3
28830,8,900,2812,2,10,8,7,o,r,n,...,0,0,0,0,0,0,0,0,0,2
94947,21,363,8973,2,10,5,5,t,r,n,...,0,0,0,0,0,0,0,0,0,3
590882,22,418,10694,2,10,6,5,t,r,n,...,0,0,0,0,0,0,0,0,0,2
201944,11,131,1488,3,30,8,9,t,r,n,...,0,0,0,0,0,0,0,0,0,3

In [6]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler
import pandas as pd

def preprocess_data(df):
    # Extract categorical features
    cat_cols = df.select_dtypes(include='object').columns
#     print(f"Categorical Feature:{cat_cols} /n length = {len(cat_cols)}")
    cat_df = df[cat_cols]
    
    # One-hot encode categorical features
    encoder = OneHotEncoder(handle_unknown='ignore')
    cat_df_encoded = encoder.fit_transform(cat_df)
    cat_df_encoded = pd.DataFrame(cat_df_encoded.toarray(), columns=encoder.get_feature_names(cat_cols), index = df.index)
    
    # Extract numerical features
    num_cols = df.select_dtypes(include=['int64']).columns
    num_df = df[num_cols]
    
    # Identify and normalize binary features
    binary_cols = [col for col in num_df.columns if num_df[col].nunique() == 2]
#     print(f"Binary Feature:{binary_cols} /n length = {len(binary_cols)} ")
    if binary_cols:
        for col in binary_cols:
            num_df[col] = num_df[col].astype(bool).astype(int)
            scaler = MinMaxScaler()
            num_df[col] = scaler.fit_transform(num_df[col].values.reshape(-1, 1))
    
    num_col = num_df.drop(binary_cols, axis=1).columns
#     print(f"Numerical Feature:{num_col}/n length = {len(num_col)} ")
    # Scale numerical features
    scaler = StandardScaler()
    num_df_scaled = scaler.fit_transform(num_df.drop(binary_cols, axis=1))
    num_df_scaled = pd.DataFrame(num_df_scaled, columns=num_cols.drop(binary_cols),index = df.index)
    
    # Combine encoded categorical, binary and scaled numerical features into a new dataframe
    df_preprocessed = pd.concat([num_df_scaled, cat_df_encoded, num_df[binary_cols]], axis=1)
    
    return df_preprocessed

In [7]:
X = train.drop('damage_grade',axis=1)
y = train['damage_grade']
X_scaled = preprocess_data(X)

In [8]:
X_scaled.index

Int64Index([802906,  28830,  94947, 590882, 201944, 333020, 728451, 475515,
            441126, 989500,
            ...
            560805, 207683, 226421, 159555, 827012, 688636, 669485, 602512,
            151409, 747594],
           dtype='int64', name='building_id', length=260601)

In [9]:
X_scaled.head(20)

,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,count_families,land_surface_condition_n,land_surface_condition_o,...,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
building_id,,,,,,,,,,,,,,,,,,,,,
802906,-0.983414,-0.518705,1.629055,-0.178274,0.047100,-0.459460,-0.226419,0.038365,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28830,-0.734459,0.481998,-0.945017,-0.178274,-0.224765,-0.004110,0.816109,0.038365,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
94947,0.883744,-0.819158,0.744612,-0.178274,-0.224765,-0.687135,-0.226419,0.038365,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
590882,1.008221,-0.685893,1.216589,-0.178274,-0.224765,-0.459460,-0.226419,0.038365,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
201944,-0.361028,-1.381296,-1.308119,1.195989,0.047100,-0.004110,1.858636,0.038365,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
333020,-0.734459,-0.346671,-0.046314,-0.178274,-0.224765,0.223565,-0.226419,0.038365,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
728451,-0.609982,-0.547781,1.592854,-0.178274,-0.020866,-1.142486,-0.747683,0.038365,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
475515,0.759267,-0.916078,1.639476,-0.178274,-0.360698,-0.004110,0.294845,0.038365,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
441126,-1.730277,0.135508,0.263584,-0.178274,-0.156799,-0.004110,0.294845,0.038365,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
989500,1.506130,0.448076,-1.443596,-1.552536,-0.360698,1.134266,-0.747683,0.038365,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7962,0.385835,1.012637,1.626312,-0.178274,-0.088832,0.223565,0.294845,0.038365,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
452227,0.385835,1.390626,-0.618116,-1.552536,-0.224765,-0.004110,-0.747683,0.038365,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
444381,-0.236551,-0.887002,0.523569,-0.178274,-0.156799,-0.459460,-0.226419,0.038365,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
287845,0.385835,0.280888,0.007164,1.195989,0.250999,-0.231785,0.816109,0.038365,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
605134,0.510312,1.439087,0.201879,-0.178274,-0.020866,-0.231785,0.294845,0.038365,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
563431,-1.232368,-0.525974,1.331772,-0.178274,0.386932,-0.914810,-0.747683,0.038365,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
633759,-0.983414,0.011934,1.647978,-0.178274,-0.292732,-0.231785,-0.226419,0.038365,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
980230,1.630607,-1.175340,1.663335,1.195989,-0.224765,-0.231785,0.816109,0.038365,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
354011,1.506130,1.695926,-0.645541,-1.552536,-0.088832,0.906591,-1.268946,0.038365,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
483543,-0.734459,-1.599367,-0.064140,-0.178274,-0.088832,1.817292,-0.747683,0.038365,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=5)

# Random Forest

In [11]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

#  Gradient Boosting Classifier without winsorizing

In [12]:
from sklearn.ensemble import GradientBoostingClassifier
gb_classifier = GradientBoostingClassifier(n_estimators=800, learning_rate=0.2, max_depth=9,min_samples_split=1600,min_samples_leaf=250,subsample=0.9)

# Fit the model to the training data
gb_classifier.fit(X_train, y_train)

GradientBoostingClassifier(learning_rate=0.2, max_depth=9, min_samples_leaf=250,
                           min_samples_split=1600, n_estimators=800,
                           subsample=0.9)

In [13]:
# Make predictions on the test data
y_pred = gb_classifier.predict(X_test)

In [14]:
# Calculate the F1 score micro
f1_micro = f1_score(y_test, y_pred, average='micro')
print(f"F1 Score Micro: {f1_micro}")

F1 Score Micro: 0.7444091418397262

In [15]:
test_scaled = preprocess_data(test)
prediction = gb_classifier.predict(test_scaled)

In [18]:
# Ensure the predictions are in teh correct submission format
submission_format = pd.read_csv('submission_format.csv',index_col = 'building_id')
result = pd.DataFrame(data=prediction,
                             columns=submission_format.columns,
                             index=submission_format.index)
result['damage_grade'] =result['damage_grade'].astype(int)
result.head()

             damage_grade
building_id
300051                  3
99355                   2
890251                  2
745817                  1
421793                  3

In [19]:
result.to_csv('my_result.csv')