In [1]:
#importing liabraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, accuracy_score, classification_report
from sklearn.metrics import confusion_matrix
import warnings
warnings.filterwarnings("ignore")

%matplotlib inline
pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",None)
plt.style.use('seaborn')

In [2]:
# importing datasets
train=pd.read_csv("train_values.csv",index_col = 0)
labels=pd.read_csv("train_labels.csv",index_col = 0)
test=pd.read_csv("test_values.csv",index_col = 0)
# adding labels to train dataset
train["damage_grade"]=labels["damage_grade"]
print("shape of the train dataset is : ",train.shape)
print("shape of the test dataset is  : ",test.shape)

shape of the train dataset is :  (260601, 39)
shape of the test dataset is  :  (86868, 38)

In [3]:
# checking the types of varibles in the dataset(int,float,object)
dtypes=pd.DataFrame(train.dtypes,columns=["Data Type"])
dtypes["Unique Values"]=train.nunique()
dtypes["Null Values"]=train.isnull().sum()
dtypes["% null Values"]=train.isnull().sum()/len(train)
dtypes

,Data Type,Unique Values,Null Values,% null Values
geo_level_1_id,int64,31,0,0.0
geo_level_2_id,int64,1414,0,0.0
geo_level_3_id,int64,11595,0,0.0
count_floors_pre_eq,int64,9,0,0.0
age,int64,42,0,0.0
area_percentage,int64,84,0,0.0
height_percentage,int64,27,0,0.0
land_surface_condition,object,3,0,0.0
foundation_type,object,5,0,0.0
roof_type,object,3,0,0.0
ground_floor_type,object,5,0,0.0
other_floor_type,object,4,0,0.0
position,object,4,0,0.0
plan_configuration,object,10,0,0.0
has_superstructure_adobe_mud,int64,2,0,0.0
has_superstructure_mud_mortar_stone,int64,2,0,0.0
has_superstructure_stone_flag,int64,2,0,0.0
has_superstructure_cement_mortar_stone,int64,2,0,0.0
has_superstructure_mud_mortar_brick,int64,2,0,0.0
has_superstructure_cement_mortar_brick,int64,2,0,0.0
has_superstructure_timber,int64,2,0,0.0
has_superstructure_bamboo,int64,2,0,0.0
has_superstructure_rc_non_engineered,int64,2,0,0.0
has_superstructure_rc_engineered,int64,2,0,0.0
has_superstructure_other,int64,2,0,0.0
legal_ownership_status,object,4,0,0.0
count_families,int64,10,0,0.0
has_secondary_use,int64,2,0,0.0
has_secondary_use_agriculture,int64,2,0,0.0
has_secondary_use_hotel,int64,2,0,0.0
has_secondary_use_rental,int64,2,0,0.0
has_secondary_use_institution,int64,2,0,0.0
has_secondary_use_school,int64,2,0,0.0
has_secondary_use_industry,int64,2,0,0.0
has_secondary_use_health_post,int64,2,0,0.0
has_secondary_use_gov_office,int64,2,0,0.0
has_secondary_use_use_police,int64,2,0,0.0
has_secondary_use_other,int64,2,0,0.0
damage_grade,int64,3,0,0.0

In [4]:
train.head(20)

,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,roof_type,ground_floor_type,other_floor_type,position,plan_configuration,has_superstructure_adobe_mud,has_superstructure_mud_mortar_stone,has_superstructure_stone_flag,has_superstructure_cement_mortar_stone,has_superstructure_mud_mortar_brick,has_superstructure_cement_mortar_brick,has_superstructure_timber,has_superstructure_bamboo,has_superstructure_rc_non_engineered,has_superstructure_rc_engineered,has_superstructure_other,legal_ownership_status,count_families,has_secondary_use,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other,damage_grade
building_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
802906,6,487,12198,2,30,6,5,t,r,n,f,q,t,d,1,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,3
28830,8,900,2812,2,10,8,7,o,r,n,x,q,s,d,0,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,2
94947,21,363,8973,2,10,5,5,t,r,n,f,x,t,d,0,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,3
590882,22,418,10694,2,10,6,5,t,r,n,f,x,s,d,0,1,0,0,0,0,1,1,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,2
201944,11,131,1488,3,30,8,9,t,r,n,f,x,s,d,1,0,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,3
333020,8,558,6089,2,10,9,5,t,r,n,f,q,s,d,0,1,0,0,0,0,0,0,0,0,0,v,1,1,1,0,0,0,0,0,0,0,0,0,2
728451,9,475,12066,2,25,3,4,n,r,n,x,q,s,d,0,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,3
475515,20,323,12236,2,0,8,6,t,w,q,v,x,s,u,0,0,0,0,0,1,1,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,1
441126,0,757,7219,2,15,8,6,t,r,q,f,q,s,d,0,1,0,0,0,0,1,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,2
989500,26,886,994,1,0,13,4,t,i,n,v,j,s,d,0,0,0,0,0,1,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,1
7962,17,1119,12188,2,20,9,6,t,r,q,f,q,t,d,0,1,0,0,0,0,1,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,3
452227,17,1275,4004,1,10,8,4,t,u,n,v,j,t,d,0,0,0,0,0,1,0,0,0,0,0,a,1,0,0,0,0,0,0,0,0,0,0,0,2
444381,12,335,8167,2,15,6,5,t,r,n,x,x,s,d,0,1,0,0,0,0,1,1,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,2
287845,17,817,6284,3,45,7,7,t,r,q,f,q,s,d,0,1,0,0,0,0,1,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,3
605134,18,1295,6994,2,25,7,6,t,r,n,f,x,s,d,0,0,1,0,0,0,1,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,3
563431,4,484,11114,2,55,4,4,n,r,n,f,q,s,d,0,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,2
633759,6,706,12267,2,5,7,5,t,r,n,f,q,t,d,0,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,2
980230,27,216,12323,3,10,7,7,t,r,n,f,q,s,d,1,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,3
354011,26,1401,3904,1,20,12,3,t,u,n,v,j,s,d,0,0,0,0,0,1,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,2
483543,8,41,6024,2,20,16,4,t,r,n,f,x,s,d,0,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0,3

In [8]:
cat_data = ['land_surface_condition', 'foundation_type', 'roof_type',
       'ground_floor_type', 'other_floor_type', 'position',
       'plan_configuration', 'legal_ownership_status']

In [9]:
catdf = train[cat_data]
catdf.head()

,land_surface_condition,foundation_type,roof_type,ground_floor_type,other_floor_type,position,plan_configuration,legal_ownership_status
building_id,,,,,,,,
802906,t,r,n,f,q,t,d,v
28830,o,r,n,x,q,s,d,v
94947,t,r,n,f,x,t,d,v
590882,t,r,n,f,x,s,d,v
201944,t,r,n,f,x,s,d,v

In [12]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler
cat_cols = train.select_dtypes(include='object').columns
print(f"Categorical Feature:{cat_cols} /n length = {len(cat_cols)}")
cat_df = train[cat_cols]

# One-hot encode categorical features
encoder = OneHotEncoder(handle_unknown='ignore')
cat_df_encoded = encoder.fit_transform(cat_df)
cat_df_encoded = pd.DataFrame(cat_df_encoded.toarray(), columns=encoder.get_feature_names(cat_cols), index = train.index)
cat_df_encoded.head()

Categorical Feature:Index(['land_surface_condition', 'foundation_type', 'roof_type',
       'ground_floor_type', 'other_floor_type', 'position',
       'plan_configuration', 'legal_ownership_status'],
      dtype='object') /n length = 8

,land_surface_condition_n,land_surface_condition_o,land_surface_condition_t,foundation_type_h,foundation_type_i,foundation_type_r,foundation_type_u,foundation_type_w,roof_type_n,roof_type_q,roof_type_x,ground_floor_type_f,ground_floor_type_m,ground_floor_type_v,ground_floor_type_x,ground_floor_type_z,other_floor_type_j,other_floor_type_q,other_floor_type_s,other_floor_type_x,position_j,position_o,position_s,position_t,plan_configuration_a,plan_configuration_c,plan_configuration_d,plan_configuration_f,plan_configuration_m,plan_configuration_n,plan_configuration_o,plan_configuration_q,plan_configuration_s,plan_configuration_u,legal_ownership_status_a,legal_ownership_status_r,legal_ownership_status_v,legal_ownership_status_w
building_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
802906,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
28830,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
94947,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
590882,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
201944,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0